config/routes.rb
Rails.application.routes.draw do

  resources :portfolio_items
  root "pages#home"

end

app/models/portfolio_item.rb
class PortfolioItem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/controllers/portfolio_items_controller.rb
class PortfolioItemsController < ApplicationController
  before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]

  # GET /portfolio_items
  # GET /portfolio_items.json
  def index
    @portfolio_items = PortfolioItem.all
  end

  # GET /portfolio_items/1
  # GET /portfolio_items/1.json
  def show
  end

  # GET /portfolio_items/new
  def new
    @portfolio_item = PortfolioItem.new
  end

  # GET /portfolio_items/1/edit
  def edit
  end

  # POST /portfolio_items
  # POST /portfolio_items.json
  def create
    @portfolio_item = PortfolioItem.new(portfolio_item_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to @portfolio_item, notice: 'Portfolio item was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio_item }
      else
        format.html { render :new }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolio_items/1
  # PATCH/PUT /portfolio_items/1.json
  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_item_params)
        format.html { redirect_to @portfolio_item, notice: 'Portfolio item was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio_item }
      else
        format.html { render :edit }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolio_items/1
  # DELETE /portfolio_items/1.json
  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolio_items_url, notice: 'Portfolio item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio_item
      @portfolio_item = PortfolioItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_item_params
      params.require(:portfolio_item).permit(:name, :url, :github_link, :desc, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolio_items_helper.rb
module PortfolioItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hall Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Shannon Hall</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Portfolio</a></li>
        <li><a href="#">Resume</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<!-- Projects -->
<div class="row">
  <div class="col-md-9">

  </div>
  <div class="col-md-3">
    I've created some things...
  </div>
</div>

<!-- Resume -->
<div class="row">
  <div class="col-md-3">
    I've done some things...
  </div>
  <div class="col-md-9">

  </div>
</div>

<!-- Contact -->
<div class="row">
  <div class="col-md-12">
    If you would like me to create or do some things for you just send me an e-mail!
  </div>
  <%=  %>
</div>

app/views/portfolio_items/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <% if @portfolio_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio_item.errors.count, "error") %> prohibited this portfolio_item from being saved:</h2>

      <ul>
      <% @portfolio_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :github_link %><br>
    <%= f.text_field :github_link %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolio_items/edit.html.erb
<h1>Editing Portfolio Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @portfolio_item %> |
<%= link_to 'Back', portfolio_items_path %>

app/views/portfolio_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Portfolio Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Github link</th>
      <th>Desc</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolio_items.each do |portfolio_item| %>
      <tr>
        <td><%= portfolio_item.name %></td>
        <td><%= portfolio_item.url %></td>
        <td><%= portfolio_item.github_link %></td>
        <td><%= portfolio_item.desc %></td>
        <td><%= portfolio_item.image %></td>
        <td><%= link_to 'Show', portfolio_item %></td>
        <td><%= link_to 'Edit', edit_portfolio_item_path(portfolio_item) %></td>
        <td><%= link_to 'Destroy', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio item', new_portfolio_item_path %>

app/views/portfolio_items/new.html.erb
<h1>New Portfolio Item</h1>

<%= render 'form' %>

<%= link_to 'Back', portfolio_items_path %>

app/views/portfolio_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @portfolio_item.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @portfolio_item.url %>
</p>

<p>
  <strong>Github link:</strong>
  <%= @portfolio_item.github_link %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @portfolio_item.desc %>
</p>

<p>
  <strong>Image:</strong>
  <%= @portfolio_item.image %>
</p>

<%= link_to 'Edit', edit_portfolio_item_path(@portfolio_item) %> |
<%= link_to 'Back', portfolio_items_path %>